spring:
  application:
    name: olive
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        linger.ms: 10
        request.timeout.ms: 500
        delivery.timeout.ms: 3000
        retry.backoff.ms: 1000
        enable.idempotence: true
      batch-size: 32768
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      acks: all

server:
  port: 8080
